### ISSUE TITLE
Adapt to recent changes with native binaries

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter.Nova.Cli#113]
Quite a few dependencies on Bluestar2 here. The CLI is no longer runnable (after https://github.com/Starcounter/Announcements/issues/73) w/o preparing setup of natives.

@Mackiovello, what's your take? Should we copy instructions from Nova README on how to manually unzip Bluestar2, or any other idea?

**Comment by Mackiovello** [comment]
I think we should move the setup instructions from the Nova README to the [getting started page](http://starcounter.github.io/Starcounter.Nova/topic-guides/getting-started.html). Then, it's publically available while still in the Nova repo. With that, we'll just link there in every place where we would need instructions.

**Comment by per-samuelsson** [comment]
> With that, we'll just link there in every place where we would need instructions.

Sounds right to me. Thanks. Want me to do it, or you?

**Comment by Mackiovello** [comment]
> Sounds right to me. Thanks. Want me to do it, or you?

I can deal with it.
