### ISSUE TITLE
Requirements for release of CLI

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#14]
Here are the required commands for the first version of this CLI:

`star list [path to directory with databases]`

Lists all databases in a directory.

- [x] https://github.com/Starcounter/Starcounter.Nova.Cli/issues/15

---

`star create [directory] [name] [options]`

Creates a database with certain options. The required options in the first iteration are:

* Collation
* First Object ID
* Last Object ID

- [x] https://github.com/Starcounter/Starcounter.Nova.Cli/issues/5 and https://github.com/Starcounter/Starcounter.Nova.Cli/issues/13

---

`star delete [directory] [options]`

Works the same as `rmdir [directory]`. Should consider having an option to only delete the directory if it contains a database `cfg` file to avoid accidentally deleting non-database directories.

- [x] https://github.com/Starcounter/Starcounter.Nova.Cli/issues/18

---

`star config [database directory]`

Lists the configuration of the database. In addition to the options set at creation, it should also be able to list things like "Memory Chunks". Check in the administrator for 2.4 to check the available configuration options.  

- [x] https://github.com/Starcounter/Starcounter.Nova.Cli/issues/19

---

`star unload [database] [options]`
`star reload [dump] [database] [options]`

Calls into StarDump to unload and reload the database.

- [x]  https://github.com/Starcounter/Starcounter.Nova.Cli/issues/20

---

`star query [query] [database] [options]`

Queries the specified database. There should be two options for fetching types:
1. Specify the assembly of the application and be able to query computed properties in addition to data properties
2. Use the StarcounterMigrationMaster to construct the types from the database. With this, it won't be possible to use computed properties
- [x] https://github.com/Starcounter/Starcounter.Nova.Cli/issues/21

There should be a `-i|--interactive` flag that opens the connection to the database and let's the user make several queries after each other. If it's not set, the tool creates a new host for every query which is slower.
- [x] https://github.com/Starcounter/Starcounter.Nova.Cli/issues/22

--- 

I also have to coordinate with @Mihaiii how to build a user interface on top of this. 

---

@miyconst did I miss something or is this it? 

**EDIT 1**: Remove `db` subcommand.
**EDIT 2**: Link to individual issues and add checkboxes

**Comment by per-samuelsson** [comment]
> I also have to coordinate with @Mihaiii how to build a user interface on top of this.

When designing, try to abstract away anything relating to the console and set your mind not to think about a CLI at all. Maybe the command pattern make most sense, but that is not as important as the former.

> Looking at this, it seems like the db subcommand is redundant. It might be neater just to ditch it.

I don't think you should consider `db` a command. Commands should normally be verbs IMO. I think the way `git` CLI is structured make good sense.

```
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect     Use binary search to find the commit that introduced a bug
   grep       Print lines matching a pattern
   log        Show commit logs
   show       Show various types of objects
   status     Show the working tree status

grow, mark and tweak your common history
   branch     List, create, or delete branches
   checkout   Switch branches or restore working tree files
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   merge      Join two or more development histories together
   rebase     Reapply commits on top of another base tip
   tag        Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch      Download objects and refs from another repository
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
```

**Comment by per-samuelsson** [comment]
> Creates a database with certain options. The **required** options in the first iteration are:

There are almost always sensible defaults. I'd say try keep required options to a minimum. Collation default could be english, or "the one that fits the system"; first and last in range - well, min and max would do pretty good. 😃

**Comment by Mackiovello** [comment]
> There are almost always sensible defaults. I'd say try keep required options to a minimum. Collation default could be english, or "the one that fits the system"; first and last in range - well, min and max would do pretty good. smiley

I meant _required_ options as in it's a requirement to be able to set them when creating the database, not that we require that you set them when you create a database. I'm using the defaults from Nova if they aren't set by the user.  

> I don't think you should consider db a command. Commands should normally be verbs IMO. I think the way git CLI is structured make good sense.

Good point, it's the same with the `dotnet` CLI. Instead of, for example, `star [db/server/app] start` it should be `star start [db/server/app]`

**Comment by per-samuelsson** [comment]
> I meant _required_ options as in it's a requirement to be able to set them when creating the database ...

Ah, sorry, my bad. Then it make sense. 👍 

> Good point, it's the same with the `dotnet` CLI. Instead of, for example, `star [db/server/app] start` it should be `star start [db/server/app]`

That's also consistent in flavor with our existing `staradmin` tooling from 2.x, even though we should not mimic that 1-1 (there are some quite ugly decisions there):

```
Usage: staradmin [options] <command> [<command options>] [<parameters>]

Options:
  --help                 Shows help about staradmin.exe
  --database=<name>      Specifies the database commands run against
  --serverhost=<host>    Specifies the admin server host
  --serverport=<port>    Specifies the admin server port

Commands:
  console    Shows console output from applications
  delete     Deletes various types of objects, e.g. databases.
  help       Shows help about a command
  kill       Kills processes relating to Starcounter
  list       List various types of objects, e.g. databases or applications.
  new        Creates various types of objects, e.g. databases or applications.
  start      Starts various types of objects, e.g. databases or the server.
  stop       Stops various types of objects, e.g. databases or applications.
```

**Comment by miyconst** [comment]
@Mackiovello the original post seems to have all the required items for the first iteration.

>When designing, try to abstract away anything relating to the console and set your mind not to think about a CLI at all. Maybe the command pattern make most sense, but that is not as important as the former.

Thanks @per-samuelsson. @Mackiovello it looks like the `[UI] - [DLL] - [CLI]` design we discussed is the way to go, while `[DLL] - [CLI] - UI` is not that good.

**Comment by Mackiovello** [comment]
> @Mackiovello it looks like the [UI] - [DLL] - [CLI] design we discussed is the way to go, while [DLL] - [CLI] - UI is not that good.

Fair enough. So I'll create a library with all the required functionality and then add a CLI application that depends on the library for all its commands. I think that gives it a nice and clean separation. It also simplifies testing somewhat.

**Comment by miyconst** [comment]
![image](https://user-images.githubusercontent.com/6435556/45545605-1625bd80-b81b-11e8-8cf6-df6f1d0efea4.png)

Please let me know when it's available to consume, and I will start using it immediately.

**Comment by Mackiovello** [comment]
Version 0.2.0 that fixes all the issues in OP is released: https://github.com/Starcounter/Starcounter.Nova.Cli/releases/tag/0.2.0

I still have a number of bugs to fix, but the tool is usable at this point. 

Closing this as done.

**Comment by Mihaiii** [comment]
I'm totally jealous for that wow image. 😄
