### ISSUE TITLE
Use Starcounter.DbConverter to get types from database for SQL command

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#21]
It should be an option for the `sql` command, from #14:

 > `star sql [query] [database] [options]`
 Queries the specified database. There should be two options for fetching types:
>  1.  Specify the assembly of the application and be able to query computed properties in addition to data properties
>  2. Use the StarcounterMigrationMaster to construct the types from the database. With this, it won't be possible to use computed properties

This issue is for implementing the second point.

**Comment by miyconst** [comment]
Requires - [Rename to Starcounter.DbConverter and release a NuGet package](https://github.com/Starcounter/StarcounterMigrationMaster/issues/58).

**Comment by Mackiovello** [comment]
Blocked by https://github.com/Starcounter/Starcounter.DbConverter/issues/82

**Comment by Mackiovello** [comment]
After talking to @linkdata, this doesn't seem like a great idea. The issue is that the approach is invasive since it requires us to create a lot of source files. It's also problematic because it requires a development environment on the machine that uses the tool since we have to compile the files.

A better approach is to generate classes dynamically. Nova does this already, so we only have to extend it to be able to take an interface and generate database classes from that. With that, we can traverse the database  metadata and feed the information to the Nova generator that creates the classes for us.

**Comment by Mackiovello** [comment]
This works partially now:

```
$ star2 query "SELECT p FROM TestPerson p" ../../test/TestProjects/CreateDatabaseTestProject/TestDatabase

| Age | Name |
| 43 | John Doe |
| 42 | Jane Doe |
```

The formatting is not perfect, but it demonstrates that it works. 

The case that doesn't work now is to query a database class that references another database class in a property.

**Comment by Mackiovello** [comment]
Steps left, in no particular order, as far as I know:
- [ ] Release new version of Nova since it contains new APIs that we need, this will only work locally with packaged Nova otherwise
- [ ] Make it possible to query database classes that reference each other in their properties
- [ ] Format output properly

**Comment by linkdata** [comment]
I think the markdown output is reasonable. Maybe have an option for different output formats in the future?
