### ISSUE TITLE
Add an "--interactive" option to the "sql" command

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#22]
From #14:

> There should be a -i|--interactive flag that opens the connection to the database and let's the user make several queries after each other. If it's not set, the tool creates a new host for every query which is slower.

**Comment by per-samuelsson** [comment]
What about supporting that with only `star sql` instead of a flag?

**Comment by Mackiovello** [comment]
> What about supporting that with only star sql instead of a flag?

So that `star sql` creates the host and opens the connection to the database and `star sql [query]` executes in the host and then exits? I think that makes sense, thanks for the suggestion!

**Comment by Mackiovello** [comment]
This is how the command looks now:

```
$ dotnet run -p src/Starcounter.Nova.Cli/Starcounter.Nova.Cli.csproj -- query --help
Execute SQL queries in a database. If you don't specify a query,
an interactive session starts where you can execute multiple queries
towards the same database without reconnecting to the database.

Usage:  query [arguments] [options]

Arguments:
  query                 The SQL query to execute

Options:
  -d|--database <PATH>  Path to the database directory
  -a|--assembly <PATH>  Path to the assembly that created the database
  -p|--project <PATH>   Path to the project that created the database.
  -?|-h|--help          Show help information
```

The implementation is not perfect yet. I need some user to test to know how people want it, but it works right now to execute multiple queries in a row without creating a new host.

**Comment by per-samuelsson** [comment]
> `dotnet run -p src/Starcounter.Nova.Cli/Starcounter.Nova.Cli.csproj -- query --help`

What's up with that syntax, with hyphens before the command? Typo, yes?

**Comment by Mackiovello** [comment]
> What's up with that syntax, with hyphens before the command? Typo, yes?

This is just for when you call it directly when it's not packaged. The stuff after the double hyphen is the arguments that you pass to `Main`; the arguments before are passed to `dotnet run`. When it's packaged, it'll be `star query --help`.
