### ISSUE TITLE
Unable to query classes with inheritance

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#49]
If we try to query classes that look like this, the query fails with `ScErrInvalidObjectAccess`:

```cs
[Database]
public class TestPerson
{
    public virtual string Name { get; set; }
    public virtual int Age { get; set; }
}

[Database]
public class InheritedPerson : TestPerson
{

}
```

Adding more information later.

**Comment by Mackiovello** [comment]
More info:

```
Exception has occurred: CLR/System.Reflection.TargetInvocationException
An exception of type 'System.Reflection.TargetInvocationException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Exception has been thrown by the target of an invocation.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Starcounter.Nova.StarcounterException : ScErrInvalidObjectAccess (SCERR4174): The operation failed because of an invalid object access. 
   at Starcounter.Nova.Database.CrudDependencies.CheckMetalayerError(UInt32 errorCode)
   at Starcounter.BluestarFFI.DbCrud.GetLong(UInt64 dbId, UInt64 dbRef, UInt64 crudHandle)
``` 

It crashes on the line where we try to access the `Name` property of `InheritedPerson` with reflection.


Stacktrace:
```
"   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n   at Starcounter.Nova.Administration.CommandLineSqlResult.<>c__DisplayClass8_0.<GetRow>b__0(PropertyInfo c) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/CommandLineSqlResult.cs:line 46\n   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()\n   at System.String.Join(String separator, IEnumerable`1 values)\n   at Starcounter.Nova.Administration.CommandLineSqlResult.ConstructRow(IEnumerable`1 values) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/CommandLineSqlResult.cs:line 51\n   at Starcounter.Nova.Administration.CommandLineSqlResult.GetRow(IDbProxy row) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/CommandLineSqlResult.cs:line 46\n   at Starcounter.Nova.Administration.CommandLineSqlResult.ToString() in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/CommandLineSqlResult.cs:line 33\n   at Starcounter.Nova.Administration.NonHostedQueryExecuter.<>c__DisplayClass0_0.<Execute>b__0() in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/NonHostedQueryExecuter.cs:line 27\n   at Starcounter.Nova.Database.Context.Run[T](Transaction txn, Func`1 fn)\n   at Starcounter.Nova.Database.Context.Transact[T](Func`1 function, TransactOptions options)\n   at Starcounter.Nova.Database.TransactImpl.Transact[T](Func`1 function, TransactOptions options)\n   at Starcounter.Nova.Administration.NonHostedQueryExecuter.Execute(String query) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/NonHostedQueryExecuter.cs:line 18\n   at Starcounter.Nova.Administration.Query.Call(String query) in /home/erlend/Starcounter/Starcounter.Nova.Cli/src/Starcounter.Nova.Administration/Sql/Query.cs:line 34\n   at Starcounter.Nova.Administration.Integration.SqlCommandTests.CanQueryDatabase() in /home/erlend/Starcounter/Starcounter.Nova.Cli/test/Starcounter.Nova.Administration.Integration/SqlCommandTests.cs:line 41"
```

**Comment by Mackiovello** [comment]
I think I've found the problem. `__dbId` and `__dbRef` is inherited when they shouldn't be. This is a bug in my `InheritedClassBuilder` in Nova.

![screenshot from 2018-08-16 11-38-18](https://user-images.githubusercontent.com/19392292/44201316-39d8e380-a149-11e8-9bb2-0a09340ede5c.png)

**Comment by Mackiovello** [comment]
Okay. Now I don't understand. `__dbId` and `__dbRef` are both declared with `FieldAttributes.Private`. 

After experimenting, this seems correct:

```cs
using System.Reflection;

namespace Reprod
{
    public class TestClass
    {
        private long _something;
    }

    class Program
    {
        static void Main(string[] args)
        {
            var type = typeof(TestClass);
            var field = type.GetField("_something", BindingFlags.NonPublic | BindingFlags.Instance);
            System.Console.WriteLine(field.Attributes); // => Private
        }
    }
}
```

The only reason I can see why the derived class gets the fields of the parent class is here: https://stackoverflow.com/a/2950842.

**Comment by Mackiovello** [comment]
To summarize, this is what we're doing:
1. Extracting metadata about the database from metalayer
2. Building a C# data model from that metadata
3. Emit C# classes representing the tables in the database based on the C# data model
4. Bind these emitted classes to the database
5. Query the classes
6. To get the result from the query, we use reflection to enumerate over the properties and print them

In this issue, we hit an exception in step 6 where we try to access the inherited properties with [PropertyInfo.GetValue](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.propertyinfo.getvalue?view=netframework-4.7.2#System_Reflection_PropertyInfo_GetValue_System_Object_). It seems to be because of invalid `__dbId` and `__dbRef` fields that are inherited from the parent with the value 0. 

@linkdata do you have an idea of why this happens?

**Comment by linkdata** [comment]
Not sure. I'll make a guess.

Previously, only the single dynamically generated subclass had these fields. If you generate them into all ancestors, that's going to be wrong. At best, you will end up with multiple copies of them, wasting space. 

For your case, where you're generating a tree of classes, they should be `protected` and live in the top-level parent (`MoaL` or equivalent). You could place them in a common base class for your use case and inherit from that.

**Comment by Mackiovello** [comment]
> For your case, where you're generating a tree of classes, they should be protected and live in the top-level parent (MoaL or equivalent). You could place them in a common base class for your use case and inherit from that.

That worked! Thanks

The fix is now merged to the [WIP PR](https://github.com/Starcounter/Starcounter.Nova.Cli/pull/50) for #21. With that, I'll consider this issue fixed
