### ISSUE TITLE
Add to TeamCity Nova integration builds

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#62]
Since this is an important part of Nova, it would be great if it was a part of the TeamCity Nova integration builds.

Right now, we're running CI with TravisCI which works well. The problem is that it doesn't run integration tests and we don't know if changes in Nova or something else breaks this CLI. 

Is there anything I can do to help get this on TeamCity?  

CC @ubbeK

**Comment by ubbeK** [comment]
> Is there anything I can do to help get this on TeamCity?

What does it need in terms of NuGet packages? Pretty much everything, right? Then we add Bifrost scripts and run it last in current Nova integration build. Does it sound feasible?

**Comment by ubbeK** [comment]
@iqbalskd

**Comment by Mackiovello** [comment]
> What does it need in terms of NuGet packages?

The only project that's used as a NuGet package is `Starcounter.Nova.Cli.Abstractions` in StarDump and Starcounter.DbConverter. 

It doesn't have any scripts for packing, pushing etc. I've done that manually when needed. 

You have to consider that `Starcounter.Nova.Cli.Abstractions` is used in StarDump and DbConverter, and `Starcounter.Nova.Cli` depends on StarDump and DbConverter. So `Starcounter.Nova.Cli.Abstractions` has to be built and packed before StarDump and DbConverter, and `Starcounter.Nova.Cli` has to be built and tested after that. 

`%STAR_NUGET%` is already set up.

I'm not sure if there's anything else worth mentioning. Don't hesitate to ask if you're wondering anything.

**Comment by per-samuelsson** [comment]
> > What does it need in terms of NuGet packages?
> 
> The only project that's used as a NuGet package is `Starcounter.Nova.Cli.Abstractions` in StarDump and Starcounter.DbConverter. 

Maybe @ubbeK also asked about dependencies of `Starcounter.Nova.Cli` itself? If so, it currently depend on most `Starcounter.Nova` packages, via `Starcounter.Nova.AspNetCore`. And `Bluestar2`. And `McMaster.Extensions.CommandLineUtils`.

Correct me if I'm wrong @Mackiovello.

**Comment by Mackiovello** [comment]
> Correct me if I'm wrong @Mackiovello.

That seems correct, the dependencies are:
- [CommandLineUtils](https://github.com/natemcmaster/CommandLineUtils)
- Nova
- Bluestar2 
- [StarDump](https://github.com/Starcounter/StarDump/)
- [Starcounter.DbConverter](https://github.com/Starcounter/Starcounter.DbConverter)

**Comment by ubbeK** [comment]
> Maybe @ubbeK also asked about dependencies of Starcounter.Nova.Cli itself?

True. 

> That seems correct, the dependencies are:
> 
> CommandLineUtils
> Nova
> Bluestar2
> StarDump
> Starcounter.DbConverter

All of those packages has been created at the end of current Nova Integration build, hence running those targets last should do fine.

**Comment by ubbeK** [comment]
@Mackiovello Should this also be built on Linux Nova Integration builds?

**Comment by Mackiovello** [comment]
> @Mackiovello Should this also be built on Linux Nova Integration builds?

Yes, it would make sense to run on both Linux and Windows. Would there be any reason for it not to? As I understand it, StarDump is cross-platform but the tests are not.

**Comment by ubbeK** [comment]
@Mackiovello How is this packed and consumed? Do you have any current scripts for it?

**Comment by ubbeK** [comment]
@iqbalskd 

* Take https://github.com/Starcounter/Products.Mapper/blob/master/build.cake as a template.
  * Private namespace
  * `RunTarget()` only if invoked from Bifrost
  * keep local variable names generic, example: `string configuration = Argument("configuration", "Debug");`
  * How to call tests may be found in Nova cake file: https://github.com/Starcounter/Starcounter.Nova/blob/develop/bifrost/Nova.cake

I think we need for independent targets (depending on @Mackiovello response above)
* `RestoreNovaCliI`
* `BuildNovaCliI`
* `TestNovaCliI`
* `PackNovaCliI`

**Comment by Mackiovello** [comment]
> @Mackiovello How is this packed and consumed? Do you have any current scripts for it?

Since it's just `Starcounter.Nova.Cli.Abstractions` that's consumed by other packages, I've just done it manually with `dotnet pack`, so no script. It's consumed in StarDump and Starcounter.DbConverter. 

So to pack, it's enough to do `dotnet pack src/Starcounter.Nova.Cli.Abstractions/Starcounter.Nova.Cli.Abstractions.csproj -o %STAR_NUGET% --configuration Release`

**Comment by ubbeK** [comment]
> Does that answer your question?

Yes, thanks!

**Comment by ubbeK** [comment]
This issue is blocked by: https://github.com/Starcounter/Starcounter.Nova.Cli/issues/82

@iqbalskd You can still continue with adding VCS roots to all of the Nova builds, both integration and publishednuget

**Comment by iqbalskd** [comment]
Added Nova.Cli in the Nova build configuration.

Closing it as done

**Comment by Mackiovello** [comment]
Thank you so much @iqbalskd! We really appreciate it

**Comment by ubbeK** [comment]
@iqbalskd What builds are now running the `PackNovaCli` target?

**Comment by iqbalskd** [comment]
Just updated the params for all Nova Integration Builds

**Comment by ubbeK** [comment]
> Just updated the params for all Nova Integration Builds

I do believe that all Nova.CLI dependencies are published, hence 4 more builds need to be updated.

**Comment by iqbalskd** [comment]
Added the `PackNovaCli ` target in these four publish builds:

- https://teamcity.starcounter.org/admin/editBuildParams.html?id=buildType:Bifrost_PubNugetNovaLinDbg

- https://teamcity.starcounter.org/admin/editBuildParams.html?id=buildType:Bifrost_PubNugetNovaLinRel

- https://teamcity.starcounter.org/admin/editBuildParams.html?id=buildType:Bifrost_PubNugetNovaWinDbg

- https://teamcity.starcounter.org/admin/editBuildParams.html?id=buildType:Bifrost_PubNugetNovaWinRel
