### ISSUE TITLE
Investigate possibility to locate databases by name when querying

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#72]
If you have a 2.4 installation, it makes sense to be able to locate by name. This is requested by @miyconst.

For example:

```
star2.exe query "SELECT * FROM Starcounter.Metadata.RawView" default
```

**Comment by eriohl** [comment]
Why not use standard SQL for this? Like: ```star2.exe query "USE default; SELECT * FROM Starcounter.Metadata.RawView"```?

**Comment by miyconst** [comment]
I don't think CLI project itself should implement any kind of SQL parsing, while our SQL engine does not support it.

**Comment by eriohl** [comment]
You don't see a problem with that statement @miyconst?

**Comment by miyconst** [comment]
>You don't see a problem with that statement @miyconst?

@eriohl I am sorry, but I am not following your question, please clarify.

**Comment by eriohl** [comment]
> > You don't see a problem with that statement @miyconst?

> @eriohl I am sorry, but I am not following your question, please clarify.

Never mind. Out of context. Please ignore.

**Comment by eriohl** [comment]
Actually: USE should not be used here anyway because what you refer to a database is not a database in the SQL meaning. We need to address this terminology issues.

**Comment by Mackiovello** [comment]
There are a number of options for how to design this API:

- Change the second argument of the `query` command to be `databaseNameOrPath` instead of `databasePath`. That would mean that we first check if it's a valid path and if there's a database at that path we use that, if not, we try to find by name. The problem with this is that it doesn't make sense on Linux, because it can't locate by database name no matter what since you can't have a 2.4 installation on Linux. 
- Add a `--use-name` flag so you can pass a database name to the `databasePath` argument: `star2 query "SELECT f FROM Foo f" default --use-name`
- Remove the `databasePath` argument and add two options: `--name` and `--path`:
  `star2 query "SELECT f FROM Foo f" --name default` or 
  `star2 query "SELECT f FROM Foo f" --path ../../MyDatabase`

Although, I'm 100% if this is the kind of thing that we want to have in this CLI. Should we try to accommodate 2.4 features into the Nova CLI? @per-samuelsson @linkdata what do you guys think? Should this be something that we should support in the Nova CLI?

**Comment by per-samuelsson** [comment]
> * Change the second argument of the `query` command to be `databaseNameOrPath` instead of `databasePath`. That would mean that we first check if it's a valid path and if there's a database at that path we use that, if not, we try to find by name. **The problem with this is that it doesn't make sense on Linux, because it can't locate by database name no matter what since you can't have a 2.4 installation on Linux.**

Just a short reflection on the highlighted section: I'm quite sure host bootstrapping API already support that, so that you can start any app with an argument passing either logical name **or** database path.

Hence, if we decide it's not right here, we should remove it from there as well.

With that being said: is it not possible that long-term, we'll have something like named databases on Linux too? At least I can say this much: I don't think we should support any of the above suggestions until we have a clear answer on the *desired* design, answering that question.

**Comment by linkdata** [comment]
> The problem with this is that it doesn't make sense on Linux, because it can't locate by database name no matter what since you can't have a 2.4 installation on Linux.

That's just a matter of following *nix practices. So if given a name we search a set of paths. One of those paths is only available on Windows ("the installation path"), but others are reasonable:

`%HOME%/.starcounter/db/[NAME]`
`/var/lib/starcounter/db/[NAME]`

etc

**Comment by Mackiovello** [comment]
> Just a short reflection on the highlighted section: I'm quite sure host bootstrapping API already support that, so that you can start any app with an argument passing either logical name or database path.

Yea. Now I feel dumb. It does work if you remove the validation that checks the database path:

```
> dotnet run -- query "SELECT p FROM Person p" default
| ID | Name     |
|----|----------|
| 1  | John Doe |
```

I think it's confusing that we're mixing concepts from Nova and level1 in this case. By using database names the way it works in level1, we're limiting ourselves when we want to have a cross-platform way to handle named databases. 

There are a couple of decisions to make here:
- Should Nova continue to support database names as they are supported in level1 by allowing `databasePathOrName` for bootstrapping?
- If we don't have that functionality in Nova, should it be moved to Starcounter.Nova.Administration or deleted?
- Do we eventually want to create a cross-platform "Nova way" of using database names?

**Comment by linkdata** [comment]
> Should Nova continue to support database names as they are supported in level1 by allowing databasePathOrName for bootstrapping?

Yes, that's my intention. There's no fundamental reason not to equate "database" with "directory" as far as I can tell, and on top of that support finding a database in some set of search paths is already in place.

> If we don't have that functionality in Nova, should it be moved to Starcounter.Nova.Administration or deleted?

It should already work. If it doesn't, it's a bug.

> Do we eventually want to create a cross-platform "Nova way" of using database names?

"Nova way" is just removing the "magic" around 2.4/level1 databases. It's already cross-platform. Or am I misunderstanding you?

**Comment by Mackiovello** [comment]
So the sensible approach then is to first make it possible to find databases by name and path in Nova tooling, and then make it possible to both create and find databases by name and path on Linux and Windows?

**Comment by linkdata** [comment]
> So the sensible approach then is to first make it possible to find databases by name and path in Nova tooling, 

Yep.

> and then make it possible to both create and find databases by name and path on Linux and Windows?

Creating by name is a bit more sensitive. I'd prefer some stricter logic here, like requiring `$HOME/.starcounter/db` to already exist before allowing creation by name only. I would not want to create databases in the current directory without it being an explicit path.

Ofc, the difference between typing `mydb` and `./mydb` is only two characters.
