### ISSUE TITLE
Decide on how to surface shared host input

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter.Nova.Cli#83]
Running the shared host is done using

`
star2 host myapp.csproj myotherapp=1.0.0
`

Today, there is no possibility to pass any parameters, neither to the shared host itself, nor to entrypoints of applications being hosted.

As an **exercise**, let's pretend we want to start the shared host on the "foo" database and pass "bar" as a single argument to the `myapp.csproj` application.

Any thoughts?

cc @Mackiovello @linkdata @miyconst

**Comment by linkdata** [comment]
An argument may contain spaces and quotations.

Having individual app names allowed as arguments is fine. Then extend it with:

`--app "theapp.csproj arg1 arg2"`

This becomes slightly more complex if you need the arguments to "theapp" to be quoted themselves, but it's doable, even with the primitive `cmd.exe`:

`--app "theapp.csproj ""arg with spaces"" arg2"`

**Comment by per-samuelsson** [comment]
Yeah, that would work passing input to individual apps. Although it's pretty damn ugly. 😀 But I don't think we can come up with anything more slick either, so.

Then args to the shared host instance would be all other then I guess? So that the exercise would render:

```
star host --database foo --app "myapp.csproj bar" --app myotherapp=1.0.0
```

**Comment by per-samuelsson** [comment]
Just want to also bring up alternatives to either split this up in a set of commands, and/or require config files for more complex scenarios.

I havent given any of them any serious thoughts though. Personally, I'd favor being able to do everything from the CLI in a single command.

**Comment by Mackiovello** [comment]
I'm not sure how the CLI option parser would handle multiple options of the same name. If so, another option would be:

```
star host --database foo --apps "myapp.csproj bar" myotherapp=1.0.0
```

I don't think that's too messy, especially since most people in my experience will run their applications without any arguments. With that, it'd look like this:

```
star host --database foo --apps myapp.csproj myotherapp=1.0.0
```

**Comment by miyconst** [comment]
I like the latest two suggestions from @per-samuelsson.

P.S. It's great to have you guys (@per-samuelsson, @linkdata, @Mackiovello ) working on Nova, I just have to leave the issue for a few hours, and you come to a good/right conclusion on your own.

**Comment by per-samuelsson** [comment]
I like what we came up to, as first suggested by @linkdata and later refined by @Mackiovello. I'm taking this into a working issue: #85.

Thanks for all input!
