### ISSUE TITLE
How do we want shared host to be started?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter.Nova.Cli#84]
When running `star host myapp.csproj`, how do we want the CLI to behave?

It should start the shared host, and...

1. spawn a new console for it, and then terminate.
2. spawn a background process, and then terminate.
3. spawn a new console, and wait for that to exit.
4. spawn a background process, redirect output streams from that to current CLI, and wait for it to exit.

cc @linkdata @bigwad @miyconst @Mackiovello

**Comment by bigwad** [comment]
If thinking in unix way.

>spawn a new console for it, and then terminate.

odd

>spawn a background process, and then terminate.

odd

>spawn a new console, and wait for that to exit.

odd

>spawn a background process, redirect output streams from that to current CLI, and wait for it to exit.

just start a process that inherits star's standard IO stream, i.e. do nothing special

It's a caller's responsibility to organize background processes if he likes

**Comment by per-samuelsson** [comment]
> just start a process that inherits star's standard IO streams, i.e. do nothing special

Ah, ok. That will work I guess. And should be pretty simple. I think it translate to something like this:

```csharp
var psi = new ProcessStartInfo() { "dotnet", "generatedhost", UseShellExecute = false };
using (var host = Process.Start(psi))
{
  host.WaitForExit();
}
```

Not sure what you meant by this though?

> It's a caller's responsibility to organize background processes if he likes

**Comment by bigwad** [comment]
>Not sure what you meant by this though?

>>It's a caller's responsibility to organize background processes if he likes

A final user is free to run `star` as a background process by using `start star..` or `star ...&` or even demonize it.

**Comment by per-samuelsson** [comment]
Thanks a lot @bigwad.

I'll adapt the suggested pattern, and will close this as **done** accordingly. Feel free to reopen if you think different and/or we should discuss more.
