### ISSUE TITLE
Consider creating separate bifrost tasks for Nova.Administration

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Nova.Cli#99]
Starcounter.Nova.Administration contains API's to to work with Nova apps and databases. Starcounter.Nova.Cli is a thin layer on top of it to expose it as a CLI. Later, we will also have other tools that will use Starcounter.Nova.Administration.

Thus, several packages will depend on Starcounter.Nova.Administration while no packages depends on Starcounter.Nova.Cli. Because of this, I think we should consider creating separate bifrost tasks so that they can be in different places in the integration builds. Nova.Cli will be last while Nova.Administration should be somewhere in the middle.

From https://github.com/Starcounter/StarDump/issues/153.

CC @ubbeK

**Comment by ubbeK** [comment]
This needs to be addressed now as I have started to work on the new generation of our [integration builds](https://github.com/Starcounter/AdminTrack/issues/564). 

* `StarDump` consumes `Starcounter.Nova.Cli.Abstractions`
* `Starcounter.Nova.Cli` consumes `StarDump`

Do you think we should break out `Starcounter.Nova.Cli.Abstractions` to its own repo or create its own set of Bifrost targets?

@Mackiovello

**Comment by Mackiovello** [comment]
> Do you think we should break out Starcounter.Nova.Cli.Abstractions to its own repo or create its own set of Bifrost targets?

I think we should have it in the same repository but with its own Bifrost targets.

Creating a whole bunch of new repositories makes it harder to keep track of things. Organizations like ASP.NET are moving to fewer repositories, see https://github.com/aspnet/Announcements/issues/320.

**Comment by ubbeK** [comment]
> Creating a whole bunch of new repositories makes it harder to keep track of things. Organizations like ASP.NET are moving to fewer repositories, see aspnet/Announcements#320.

I partially agree on this but I do think that this is a good case to keep it all in the same repo. I will just need to think through if I want a `src/Starcounter.Nova.Cli.Abstractions/build.cake` file or everything in the root `build.cake`.

**Comment by ubbeK** [comment]
>I will just need to think through if I want a src/Starcounter.Nova.Cli.Abstractions/build.cake file or everything in the root build.cake.

We will add extra targets in `build.cake`. Reasons:
* Keep down the amount of build.cake files
* minimize the amount of partially duplicate targets


As for the OP where we need extra targets for `Starcounter.Nova.Administration`. Those will be added when we need them as the origin of this issue (StarDump needing it) is using Nova directly.

**Comment by ubbeK** [comment]
Will close this as done. 

@Mackiovello If you have any opinions about the implementation, then please reopen this issue.

Closing
